#!/usr/bin/env sh
#
# Ping Identity DevOps - Docker Build Hooks
#
${VERBOSE} && set -x

# shellcheck source=../../pingcommon/hooks/pingcommon.lib.sh
. "${HOOKS_DIR}/pingcommon.lib.sh"

echo "Configuring tools.properties"
TOOLS_PROPERTIES_FILE="${SERVER_ROOT_DIR}"/config/tools.properties

mv "${TOOLS_PROPERTIES_FILE}" "${TOOLS_PROPERTIES_FILE}.orig"

_port="${LDAP_PORT}"
_useSSL="false"
_useSSL="false"

if test "${LDAP_SECURITY}" == "ssl"; then
    _port="${LDAPS_PORT}"
    _useSSL="true"
    _useStartTLS="false"
fi

if test "${LDAP_SECURITY}" == "starttls"; then
    _port="${LDAP_PORT}"
    _useSSL="false"
    _useStartTLS="true"
fi

echo "
#
# Generated by PingIdentity DevOps ${0}
#
hostname=localhost
port=${_port}
useSSL=${_useSSL}
useStartTLS=${_useStartTLS}
trustAll=true
bindDN=${ROOT_USER_DN}
bindPasswordFile=${ROOT_USER_PASSWORD_FILE}
adminUID=${ADMIN_USER_NAME}
adminPasswordFile=${ADMIN_USER_PASSWORD_FILE}
suppressPropertiesFileComment=true
" > "${TOOLS_PROPERTIES_FILE}"

